/**
 * PDF Export Utilities for WIP Reports
 * 
 * Uses html2canvas to capture the report as an image and jsPDF to generate the PDF.
 * This approach ensures the PDF matches the on-screen appearance exactly.
 */

// Dynamic imports to avoid bundling issues
let html2canvas: any = null;
let jsPDF: any = null;

const loadDependencies = async () => {
  if (!html2canvas) {
    const html2canvasModule = await import('html2canvas');
    html2canvas = html2canvasModule.default;
  }
  if (!jsPDF) {
    const jsPDFModule = await import('jspdf');
    jsPDF = jsPDFModule.jsPDF;
  }
};

export interface PDFExportOptions {
  filename: string;
  title: string;
  companyName?: string;
  companyLogo?: string;
  orientation?: 'portrait' | 'landscape';
}

/**
 * Export an HTML element to PDF
 */
export const exportToPDF = async (
  elementId: string,
  options: PDFExportOptions
): Promise<void> => {
  const element = document.getElementById(elementId);
  if (!element) {
    throw new Error(`Element with id "${elementId}" not found`);
  }

  await loadDependencies();

  // Temporarily modify styles for better PDF output
  const originalBg = element.style.background;
  element.style.background = 'white';

  try {
    // Capture the element as a canvas
    const canvas = await html2canvas(element, {
      scale: 2, // Higher quality
      useCORS: true,
      logging: false,
      backgroundColor: '#ffffff',
      windowWidth: element.scrollWidth,
      windowHeight: element.scrollHeight,
    });

    // Calculate dimensions
    const imgWidth = options.orientation === 'landscape' ? 280 : 190;
    const pageHeight = options.orientation === 'landscape' ? 190 : 280;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    
    // Create PDF
    const pdf = new jsPDF({
      orientation: options.orientation || 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    // Add header
    pdf.setFontSize(10);
    pdf.setTextColor(100);
    pdf.text(options.companyName || 'WIP Insights Report', 10, 10);
    pdf.text(new Date().toLocaleDateString(), pdf.internal.pageSize.width - 30, 10);
    
    // Add title
    pdf.setFontSize(18);
    pdf.setTextColor(0);
    pdf.text(options.title, 10, 20);

    // Add image content
    let heightLeft = imgHeight;
    let position = 30; // Start after header
    const pageWidth = pdf.internal.pageSize.width;

    // Add first page
    const imgData = canvas.toDataURL('image/png');
    pdf.addImage(imgData, 'PNG', 10, position, imgWidth, imgHeight);
    heightLeft -= (pageHeight - position);

    // Add additional pages if needed
    while (heightLeft > 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 10, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }

    // Add footer to all pages
    const totalPages = pdf.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i);
      pdf.setFontSize(8);
      pdf.setTextColor(150);
      pdf.text(
        `Page ${i} of ${totalPages}`,
        pageWidth / 2,
        pdf.internal.pageSize.height - 10,
        { align: 'center' }
      );
      pdf.text(
        'Generated by ChainLink CFO',
        10,
        pdf.internal.pageSize.height - 10
      );
    }

    // Save the PDF
    pdf.save(options.filename);
  } finally {
    // Restore original styles
    element.style.background = originalBg;
  }
};

/**
 * Export Weekly Earned Revenue Report to PDF
 */
export const exportWeeklyReportToPDF = async (companyName?: string): Promise<void> => {
  const now = new Date();
  const filename = `weekly-earned-revenue-${now.toISOString().split('T')[0]}.pdf`;
  
  await exportToPDF('weekly-earned-revenue-report', {
    filename,
    title: 'Weekly Earned Revenue Report',
    companyName,
    orientation: 'landscape',
  });
};

/**
 * Export Month-End Report to PDF
 */
export const exportMonthEndReportToPDF = async (
  month: string,
  year: number,
  companyName?: string
): Promise<void> => {
  const filename = `month-end-report-${year}-${month.toLowerCase()}.pdf`;
  
  await exportToPDF('month-end-report', {
    filename,
    title: `Month-End Report - ${month} ${year}`,
    companyName,
    orientation: 'portrait',
  });
};

/**
 * Simple table-based PDF export (alternative approach without html2canvas)
 * Useful for cleaner, more structured reports
 */
export const exportTableToPDF = async (
  data: Array<Record<string, any>>,
  columns: Array<{ header: string; key: string; width?: number }>,
  options: PDFExportOptions
): Promise<void> => {
  await loadDependencies();

  const pdf = new jsPDF({
    orientation: options.orientation || 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = pdf.internal.pageSize.width;
  const margin = 10;
  const usableWidth = pageWidth - (margin * 2);

  // Header
  pdf.setFontSize(10);
  pdf.setTextColor(100);
  pdf.text(options.companyName || 'WIP Insights', margin, 10);
  pdf.text(new Date().toLocaleDateString(), pageWidth - margin - 25, 10);

  // Title
  pdf.setFontSize(18);
  pdf.setTextColor(0);
  pdf.text(options.title, margin, 25);

  // Table header
  let yPos = 35;
  const rowHeight = 8;
  const colWidths = columns.map(col => col.width || usableWidth / columns.length);

  // Header row
  pdf.setFillColor(240, 240, 240);
  pdf.rect(margin, yPos - 5, usableWidth, rowHeight, 'F');
  pdf.setFontSize(9);
  pdf.setTextColor(80);

  let xPos = margin;
  columns.forEach((col, i) => {
    pdf.text(col.header, xPos + 2, yPos);
    xPos += colWidths[i];
  });

  yPos += rowHeight;

  // Data rows
  pdf.setTextColor(0);
  data.forEach((row, rowIndex) => {
    // Check if we need a new page
    if (yPos > pdf.internal.pageSize.height - 20) {
      pdf.addPage();
      yPos = 20;
    }

    // Alternate row background
    if (rowIndex % 2 === 0) {
      pdf.setFillColor(250, 250, 250);
      pdf.rect(margin, yPos - 5, usableWidth, rowHeight, 'F');
    }

    xPos = margin;
    columns.forEach((col, i) => {
      const value = row[col.key];
      const text = value !== undefined ? String(value) : '';
      pdf.text(text.substring(0, 30), xPos + 2, yPos); // Truncate long text
      xPos += colWidths[i];
    });

    yPos += rowHeight;
  });

  // Footer
  const totalPages = pdf.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(150);
    pdf.text(
      `Page ${i} of ${totalPages}`,
      pageWidth / 2,
      pdf.internal.pageSize.height - 10,
      { align: 'center' }
    );
  }

  pdf.save(options.filename);
};

